---
title: "lab4"
output: html_document
---
```{r}

   
   
   ggplot(data = NULL, aes(x = c(-3, 6), y = c(0, 0.4))) +
     stat_function(fun = dnorm,
                args = list(mean = 0, sd = 1),
                lwd = 1.2,
                xlim = c(-3, 3),
                color = 'blue') +
  stat_function(fun = dnorm,
                xlim = c(qnorm(0.95), 3),
                geom = "area",
                alpha = 0.6,
                color = 'black',
                aes(fill = 'B')) + 
  stat_function(fun = dnorm,
                args = list(mean = 3.2, sd = 1),
                lwd = 1.2,
                xlim = c(0, 6),
                color = 'red') +
  stat_function(fun = dnorm,
                args = list(mean = 3.2, sd = 1),
                xlim = c(0, qnorm(0.95)), 
                geom = "area",
                alpha = 0.6,
                color = 'black',
                aes(fill = 'A')) + 
     geom_vline(xintercept = qnorm(0.95), lty=2, lwd=1.2) +
     geom_text(aes(x = 1, y = 0.015), label = expression(beta), size = 7) + 
     geom_text(aes(x = 2, y = 0.015), label = expression(alpha), size = 7, col = "white") + 
     labs(x = "", y = "") + 
     theme(panel.background = element_blank(),
        legend.title = element_blank(),
        legend.justification = c(0, 1),
        legend.position = c(0, 1),
        legend.box.margin = margin(c(1.2, 1.2, 1, 1)),
        legend.box.background = element_rect(color = 'black',
                                             fill = NA),
        legend.text = element_text(size = 14,
                                   margin = margin(l = 10)),
        panel.border = element_rect( color = "black", fill = NA),
        axis.text.x = element_text(hjust = 0.5, size = 20),
        axis.text.y = element_text(angle = 90, 
                                   hjust = 0.5, 
                                   size = 14,
                                   vjust = 2),
        axis.ticks.length = unit(0.2, "cm")) + 
     scale_x_continuous(breaks = c(0, 3.2), 
                    labels = c(expression(theta[0]), expression(theta[1]))) +
     scale_fill_manual(values = c("B" = "blue",
                                 "A"= "red"), 
                      label = c("Type II error",
                                "Type I error"))
  
```

```{r}
prime_detect <- function(x){
  if( x <= 1){
    stop("x must be as least 2")
  }
  if( x != round(x)){
    stop("x must be an integer")
  }
  if(x == 2){
    return("x is a prime number")
  }
  n <- 0
  for (i in 2 : (x - 1)) {
    n <- n + sum((x %% i) == 0) 
    
  }
  if(n == 0){
    print("n is a prime number")
  }else{
    print("n is not a prime number")
  }
}
```

